= MailCleaner

== Configuration file

The file needs to be created in the `config` folder with name `config.yml`.

[source]
----
quarkus:
  log:
    category:
      "be.blit.mailcleaner":
        level: INFO
  rest-client:
    rspamd:
      url: http://rspamd:11333
mail-cleaner:
  schedule: 5m
  rspamd:
    dry-run: true
  imap:
    host: imap.example.com
    port: 993
    username: my_username
    password: my_password
  folders:
  - INBOX
  blocked-senders:
  - test1@spam.com
  - test2@spam.com
  - test3@spam.com
----

== Docker compose

[source]
----
services:
  mailcleaner:
    image: ghcr.io/leclercb/mailcleaner:main
    container_name: mailcleaner
    depends_on:
      - rspamd
    volumes:
      - /volume1/docker/mailcleaner/config:/config:rw
    ports:
      - 2180:8080
    restart: unless-stopped
  rspamd:
    image: rspamd/rspamd
    container_name: rspamd
    ports:
      - 11333:11333
    restart: unless-stopped
----

## Running the application in dev mode

You can run your application in dev mode that enables live coding using:

```shell script
./gradlew quarkusDev
```

> **_NOTE:_**  Quarkus now ships with a Dev UI, which is available in dev mode only at <http://localhost:8080/q/dev/>.

## Packaging and running the application

The application can be packaged using:

```shell script
./gradlew build
```

It produces the `quarkus-run.jar` file in the `build/quarkus-app/` directory.
Be aware that it’s not an _über-jar_ as the dependencies are copied into the `build/quarkus-app/lib/` directory.

The application is now runnable using `java -jar build/quarkus-app/quarkus-run.jar`.

If you want to build an _über-jar_, execute the following command:

```shell script
./gradlew build -Dquarkus.package.jar.type=uber-jar
```

The application, packaged as an _über-jar_, is now runnable using `java -jar build/*-runner.jar`.

## Creating a native executable

You can create a native executable using:

```shell script
./gradlew build -Dquarkus.native.enabled=true
```

Or, if you don't have GraalVM installed, you can run the native executable build in a container using:

```shell script
./gradlew build -Dquarkus.native.enabled=true -Dquarkus.native.container-build=true
```

You can then execute your native executable with: `./build/mailcleaner-1.0.0-SNAPSHOT-runner`

If you want to learn more about building native executables, please consult <https://quarkus.io/guides/gradle-tooling>.
