quarkus:
  rest-client:
    rspamd:
      url: http://rspamd:11333
mail-cleaner:
  schedule: "5m"
  rspamd:
    dry-run: true
  imap:
    host:
    port:
    username:
    password:
  folders:
  blocked-senders:
